SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING OFF
GO
CREATE TABLE [dbo].[Tabl1Na] (
		[id]     [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tabl1Na] SET (LOCK_ESCALATION = TABLE)
GO
