SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[t1newN] (
		[c11]      [int] NOT NULL,
		[c133]     [nvarchar](50) COLLATE Latin1_General_CI_AI NULL,
		[c22]      [nchar](10) COLLATE Latin1_General_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[t1newN]
	ADD
	CONSTRAINT [PK__t1__D83016C43BE5F7F8]
	PRIMARY KEY
	CLUSTERED
	([c11])
	ON [PRIMARY]
GO
ALTER TABLE [dbo].[t1newN] SET (LOCK_ESCALATION = TABLE)
GO
